export default [
  { _id: 'name', value: 'Name' },
  { _id: 'pronouns', value: 'Pronouns' },
  { _id: 'phone', value: 'Phone' },
  { _id: 'website', value: 'Website' },
  { _id: 'email', value: 'Email' },
  { _id: 'city', value: 'City' },
  { _id: 'occupation', value: 'Occupation' },
  { _id: 'address', value: 'Address' },
  { _id: 'availability', value: 'Availability' },
  { _id: 'twitter', value: 'Twitter' },
  { _id: 'insta', value: 'Instagram' },
  { _id: 'snapchat', value: 'Snapchat' },
  { _id: 'facebook', value: 'Facebook' },
  { _id: 'mastodon', value: 'Mastodon' },
  { _id: 'steam', value: 'Steam' },
  { _id: 'xbox', value: 'Xbox' },
  { _id: 'psn', value: 'PSN' },
];
